/*************************************************************
	LGE - this script was generated by Sql Server 2008
		  and tested on Sql Server 2014 Community Edition
		  
		  my database is named [oauth2test], if you use a different name
		  adjust the USE statement accordingly
		  
*************************************************************/

USE [oauth2test]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_accessTokenCache_tstamp]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[accessTokenCache] DROP CONSTRAINT [DF_accessTokenCache_tstamp]
END

GO

USE [oauth2test]
GO

/****** Object:  Table [dbo].[accessTokenCache]    Script Date: 07/09/2017 15:15:37 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[accessTokenCache]') AND type in (N'U'))
DROP TABLE [dbo].[accessTokenCache]
GO

USE [oauth2test]
GO

/****** Object:  Table [dbo].[accessTokenCache]    Script Date: 07/09/2017 15:15:37 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

SET ANSI_PADDING ON
GO

CREATE TABLE [dbo].[accessTokenCache](
	[userId] [bigint] NOT NULL,
	[accessToken] [varchar](128) NOT NULL,
	[refreshToken] [varchar](128) NOT NULL,
	[tokenLife] [int] NOT NULL,
	[tstamp] [datetime] NOT NULL,
	[responseUrl] [nvarchar](max) NOT NULL,
 CONSTRAINT [PK_accessTokenCache] PRIMARY KEY CLUSTERED 
(
	[userId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY]

GO

SET ANSI_PADDING OFF
GO

ALTER TABLE [dbo].[accessTokenCache] ADD  CONSTRAINT [DF_accessTokenCache_tstamp]  DEFAULT (getdate()) FOR [tstamp]
GO
