/*************************************************************
	LGE - this script was generated by Sql Server 2008
		  and tested on Sql Server 2014 Community Edition
		  
		  my database is named [oauth2test], if you use a different name
		  adjust the USE statement accordingly
*************************************************************/

USE [oauth2test]
GO

IF  EXISTS (SELECT * FROM dbo.sysobjects WHERE id = OBJECT_ID(N'[DF_stateCache_tstamp]') AND type = 'D')
BEGIN
ALTER TABLE [dbo].[stateCache] DROP CONSTRAINT [DF_stateCache_tstamp]
END

GO

USE [oauth2test]
GO

/****** Object:  Table [dbo].[stateCache]    Script Date: 04/06/2017 23:47:00 ******/
IF  EXISTS (SELECT * FROM sys.objects WHERE object_id = OBJECT_ID(N'[dbo].[stateCache]') AND type in (N'U'))
DROP TABLE [dbo].[stateCache]
GO

USE [oauth2test]
GO

/****** Object:  Table [dbo].[stateCache]    Script Date: 04/06/2017 23:47:00 ******/
SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

CREATE TABLE [dbo].[stateCache](
	[stateId] [uniqueidentifier] NOT NULL,
	[stateJson] [text] NOT NULL,
	[tstamp] [datetime] NOT NULL,
 CONSTRAINT [PK_stateCache] PRIMARY KEY CLUSTERED 
(
	[stateId] ASC
)WITH (PAD_INDEX  = OFF, STATISTICS_NORECOMPUTE  = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS  = ON, ALLOW_PAGE_LOCKS  = ON) ON [PRIMARY]
) ON [PRIMARY] TEXTIMAGE_ON [PRIMARY]

GO

ALTER TABLE [dbo].[stateCache] ADD  CONSTRAINT [DF_stateCache_tstamp]  DEFAULT (getdate()) FOR [tstamp]
GO


